- id: '1589626031994'
  alias: Perform Daily Backup
  trigger:
    platform: time
    at: 00:00:00
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: 'DailyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
      keep_days: 7
- id: '1590333653446'
  alias: Notify Snapshot Failure
  trigger:
    platform: event
    event_type: auto_backup.snapshot_failed
  action:
    service: persistent_notification.create
    data_template:
      title: Snapshot Failed.
      message: 'Name: {{ trigger.event.data.name }}

        Error: {{ trigger.event.data.error }}'
