homeassistant:
  name: Home

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  time_zone: !secret time_zone
  unit_system: imperial
  temperature_unit: F

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

# Includes
automation: !include config/automation.yaml
amcrest: !include config/amcrest.yaml
binary_sensor: !include config/binary_sensor.yaml
camera: !include_dir_list config/cameras/
cover: !include_dir_list config/covers/
ecobee: !include config/ecobee.yaml
discovery: !include config/discovery.yaml
group: !include config/group.yaml
http: !include config/http.yaml
hue: !include config/hue.yaml
ifttt: !include config/ifttt.yaml
input_boolean: !include_dir_merge_named config/input_boolean/
light: !include_dir_list config/lights/
logger: !include config/logger.yaml
lutron_caseta: !include config/lutron_caseta.yaml
media_player: !include config/media_player.yaml
mqtt: !include config/mqtt.yaml
nest: !include config/nest.yaml
notify: !include config/notify.yaml
nuheat: !include config/nuheat.yaml
panel_iframe: !include config/panel_iframes.yaml
recorder: !include config/recorder.yaml
sensor: !include config/sensor.yaml
shell_command: !include config/shell_command.yaml
tts: !include config/tts.yaml
#usps: !include config/usps.yaml
weather: !include config/weather.yaml
wemo: !include config/wemo.yaml
zone: !include config/zones.yaml
zwave: !include config/zwave.yaml

# Base configuration
cloud:
config:
conversation:
frontend:
hassio:
history:
ios:
logbook:
map:
sun:
updater:
