homeassistant:
  name: Home

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  time_zone: !secret time_zone
  unit_system: imperial
  temperature_unit: F

  packages: !include_dir_named packages

# Includes
amcrest: !include config/amcrest.yaml
camera: !include_dir_list config/cameras/
cover: !include_dir_list config/covers/
ecobee: !include config/ecobee.yaml
group: !include config/groups.yaml
http: !include config/http.yaml
ifttt: !include config/ifttt.yaml
logger: !include config/logger.yaml
nest: !include config/nest.yaml
panel_iframe: !include config/panel_iframes.yaml
shell_command: !include config/shell_command.yaml
tts: !include config/tts.yaml
weather: !include config/weather.yaml
zone: !include config/zones.yaml
zwave: !include config/zwave.yaml

# Base configuration
cloud:
config:
conversation:
discovery:
frontend:
hassio:
history:
logbook:
map:
sun:
updater:
