homeassistant:
  name: Home

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  time_zone: !secret time_zone
  unit_system: imperial
  temperature_unit: F

  packages: !include_dir_named packages

# Includes
group: !include config/groups.yaml
http: !include config/http.yaml
logger: !include config/logger.yaml
zone: !include config/zones.yaml
panel_iframe: !include config/panel_iframes.yaml
tts: !include config/tts.yaml
weather: !include config/weather.yaml
camera: !include_dir_list config/cameras/
amcrest: !include config/amcrest.yaml

# Base configuration
cloud:
config:
conversation:
discovery:
frontend:
hassio:
history:
logbook:
map:
sun:
updater: