# Base configuration
default_config:
hassio:

# Includes
alarm_control_panel: !include config/alarm_control_panel.yaml
amcrest: !include config/amcrest.yaml
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list config/binary_sensor/
browser_mod:
camera: !include_dir_merge_list config/cameras/
cover: !include_dir_merge_list config/covers/
ffmpeg:
folder_watcher: !include config/folder_watcher.yaml
frontend: !include config/frontend.yaml
google: !include config/google.yaml
group: !include config/group.yaml
hacs: !include config/hacs.yaml
homeassistant: !include config/homeassistant.yaml
homekit: !include config/homekit.yaml
http: !include config/http.yaml
image_processing: !include config/image_processing.yaml
influxdb: !include config/influxdb.yaml
light: !include_dir_list config/lights/
ios: !include config/ios.yaml
kohler: !include config/kohler.yaml
logger: !include config/logger.yaml
lutron_caseta: !include config/lutron_caseta.yaml
microsoft_face: !include config/microsoft_face.yaml
nest: !include config/nest.yaml
notify: !include config/notify.yaml
#octoprint: !include config/octoprint.yaml
panel_iframe: !include config/panel_iframe.yaml
recorder: !include config/recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list config/sensor/
shell_command: !include config/shell_command.yaml
spotify: !include config/spotify.yaml
stream:
switch: !include_dir_merge_list config/switch/
tts: !include config/tts.yaml
wake_on_lan:
weather: !include config/weather.yaml
webostv: !include config/webostv.yaml
wirelesstag: !include config/wirelesstag.yaml