title: Home

resources:
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/custom_ui/monster-card.js
    type: js

views:
  - icon: mdi:home
    id: home
    title: home
    cards:
#      - type: entity-filter
#        entities:
#          - !secret person_1_device_tracker_id
#          - !secret person_2_device_tracker_id
#        state_filter:
#          - home
#          - !secret zone_1_name
#        card:
#          type: glance
#          title: Who is Home?
#          show_state: false
#          show_name: true
      - type: entities
        title: Trash & Recycling Schedule
        entities:
          - sensor.trash_day
          - sensor.recycle_day
      - type: custom:monster-card
        card:
          type: entities
          title: Climate Control
        filter:
          include:
            - domain: climate
      - type: custom:monster-card
        card:
          type: glance
          title: Lighting
        filter:
          include:
            - domain: light
      - type: custom:monster-card
        card:
          type: glance
          title: Fans
        filter:
          include:
            - domain: fan
      - type: custom:monster-card
        card:
          type: glance
          title: Switches
        filter:
          include:
            - domain: switch
      - type: custom:monster-card
        card:
          type: entities
          title: Media
        filter:
          include:
            - domain: media_player

  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: custom:weather-card
        entity_weather: weather.yweather
        entity_sun: sun.sun
      - type: entities
        title: Weather
        entities:
          - sun.sun
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary
          - sensor.dark_sky_visibility
          - sensor.dark_sky_wind_bearing
          - sensor.dark_sky_wind_speed
          - sensor.allergy_index_today
          - sensor.us_air_pollution_level
      - type: picture-entity
        entity: camera.wunderground_radar
      - type: iframe
        aspect_ratio: 90%
        url: https://embed.windy.com/embed2.html?rain,44.5133,-88.0133,10

  - icon: mdi:security-home
    name: Security
    cards:
      - type: entities
        title: Doors
        entities:
          - lock.unknown_id033f_unknown_type0001_id0001_locked
          - cover.house_left_garage_door_opener
          - cover.house_right_garage_door_opener
          - cover.left_garage_door
      - type: entities
        title: Motion
        entities:
          - sensor.living_room_motion_detected
          - binary_sensor.front_door_camera_motion_detected
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.front_door_camera_sound_detected

  - icon: mdi:cctv
    id: cameras
    title: Cameras
    cards:
      - type: picture-entity
        entity: camera.front_door
      - type: picture-entity
        entity: camera.living_room

  - icon: mdi:settings
    id: settings
    title: settings
    cards:
      - type: entities
        title: Trash Schedule
        entities:
          - sensor.trash_day
          - sensor.trash_pickup_day
          - input_select.trash_pickup_day
      - type: entities
        title: Recycle Schedule
        entities:
          - sensor.recycle_day
          - sensor.recycle_pickup_day
          - sensor.recycle_pickup_week
          - input_select.recycle_pickup_day
          - sensor.current_week
          - input_select.recycle_pickup_week