title: Home

resources:
  - url: /local/custom_ui/weather-card.js
    type: js

views:
  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: custom:weather-card
        entity_weather: weather.yweather
        entity_sun: sun.sun
      - type: entities
        title: Weather
        entities:
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary
      - type: picture-entity
        entity: camera.wunderground_radar
      - type: iframe
        aspect_ratio: 90%
        url: https://embed.windy.com/embed2.html?rain,44.5133,-88.0133,10

  - icon: mdi:security-home
    name: Security
    cards:
      - type: entities
        title: Doors
        show_header_toggle: true
        entities:
          - lock.unknown_id033f_unknown_type0001_id0001_locked
          - cover.house_left_garage_door_opener
          - cover.house_right_garage_door_opener
      - type: entities
        title: Motion
        entities:
          - sensor.living_room_motion_detected
          - binary_sensor.front_door_camera_motion_detected
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.front_door_camera_sound_detected

  - icon: mdi:cctv
    id: cameras
    title: Cameras
    cards:
      - type: picture-entity
        entity: camera.front_door
      - type: picture-entity
        entity: camera.living_room