automation_enable:
  name: Enable Automations
  icon: mdi:home-automation

automation_normalize_volume:
  name: Automation - Automatically Normalize Volume throughout the day
  icon: mdi:volume-high

automation_outside_front_lights_on_motion:
  name: Automation - Turn On/Off Outside Front Lights (Motion)
  icon: mdi:lightbulb-on

automation_outside_front_lights:
  name: Automation - Outside Front Lights
  icon: mdi:lightbulb-on

automation_outside_front_can_lights:
  name: Automation - Outside Front Can Lights
  icon: mdi:lightbulb-on

automation_outside_back_lights:
  name: Automation - Outside Back Lights
  icon: mdi:lightbulb-on

automation_outside_lights_on_garage_door_activity:
  name: Automation - Turn On/Off Outside Lights on Garage Door Activity
  icon: mdi:lightbulb-on

automation_inside_lamp_lights:
  name: Automation - Turn On/Off Inside Lamp Lights
  icon: mdi:lightbulb-on

automation_inside_unlock_doors_on_garage_door_open:
  name: Automation - Automatically Unlock doors Garage Door Open
  icon: mdi:lock-open

automation_inside_lock_doors_on_garage_door_close:
  name: Automation - Automatically Lock doors Garage Door Close
  icon: mdi:lock

automation_inside_lights_on_garage_door_activity:
  name: Automation - Turn On/Off Inside Lights on Garage Door Activity
  icon: mdi:lightbulb-on

automation_inside_lights_on_motion:
  name: Automation - Turn On/Off Inside Lights (Motion)
  icon: mdi:lightbulb-on

automation_inside_closet_lights:
  name: Automation - Turn Off Lights closet lights
  icon: mdi:lightbulb-on

automation_inside_turn_off_lights_inactivity:
  name: Automation - Turn Off Lights on inactivity.
  icon: mdi:lightbulb-on

automation_inside_fireplace:
  name: Automation - Automatically Turn On/Off Fireplace
  icon: mdi:fire

automation_inside_bathroom_fans:
  name: Automation - Automatically Turn On/Off Bathroom Fans
  icon: mdi:fan

automation_inside_master_bedroom_fan:
  name: Automation - Master Bedroom Fan
  icon: mdi:fan

automation_emergency_lights_on:
  name: Turn on Lights during emergency
  icon: mdi:alarm-light

automation_emergency_siren_on:
  name: Open garage door during emergency
  icon: mdi:speaker-wireless

automation_emergency_garage_door_open:
  name: Open garage door during emergency
  icon: mdi:door-open

automation_emergency_unlock_doors:
  name: Open garage door during emergency
  icon: mdi:door-open