guest_mode:
  name: Guest Mode
  icon: mdi:hotel

do_not_disturb_mode:
  name: Do Not Disturb
  icon: mdi:bell-off

vacation_mode:
  name: Vacation Mode
  icon: mdi:beach

emergency_mode:
  name: Emergency Mode
  icon: mdi:exit-run

facial_recognition_mode:
  name: Use Facial Recognition
  icon: mdi:face-profile