sensor:
  - platform: airvisual
    api_key: !secret airvisual_api_key
  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
      - summary
      - cloud_cover
      - icon
      - daily_summary
      - hourly_summary

      # - Added for dashboard
      - humidity
      - temperature
      - wind_bearing
      - wind_speed
      - visibility
    scan_interval:
      minutes: 5
  - platform: illuminance
    name: Illuminance
    entity_id: weather.dark_sky