sensor:
  - platform: airvisual
    api_key: !secret airvisual_api_key
  - platform: pollen
    zip_code: !secret zip_code
    monitored_conditions:
      - allergy_average_forecasted
      - allergy_average_historical
      - allergy_index_today
      - allergy_index_tomorrow
      - allergy_index_yesterday
      - disease_average_forecasted
  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
      - summary
      - cloud_cover
      - icon
      - daily_summary
      - hourly_summary

      # - Added for dashboard
      - humidity
      - temperature
      - wind_bearing
      - wind_speed
      - visibility
    update_interval:
      minutes: 5
  - platform: illuminance
    name: Dark Sky Illuminance
    entity_id: sensor.dark_sky_icon
  - platform: season