- platform: template
  sensors:
    last_alexa:
      value_template: >
        {%- for entity in states.media_player -%}
          {%- if state_attr(entity.entity_id, 'last_called') == True -%}
            {{ entity.entity_id }}
          {%- endif -%}
        {%- endfor -%}
