- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - alerts
    - summary
    - cloud_cover
    - icon
    - daily_summary
    - hourly_summary

    # - Added for dashboard
    - humidity
    - temperature
    - wind_bearing
    - wind_speed
    - visibility
  scan_interval:
    minutes: 15

- platform: template
  sensors:
    dark_sky_alert_text:
      friendly_name: "Weather Alert Text"
      value_template: >-
        {% if is_state("sensor.dark_sky_alerts", "0") %}
          No Weather Alerts
        {% elif is_state("sensor.dark_sky_alerts", "1") %}
          {{ states.sensor.dark_sky_alerts.attributes.title }}
        {% else %}
          {{ states.sensor.dark_sky_alerts.attributes.title_0 }}
        {% endif %}