- platform: rest
  name: Frigate Debug
  resource: !secret frigate_debug_states_url
  scan_interval: 5
  json_attributes:
    - back
    - coral
  value_template: 'OK'  
- platform: template
  sensors:
    back_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["back"]["fps"] }}'
      unit_of_measurement: 'FPS'
    back_skipped_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["back"]["skipped_fps"] }}'
      unit_of_measurement: 'FPS'
    back_detection_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["back"]["detection_fps"] }}'
      unit_of_measurement: 'FPS'
    frigate_coral_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["fps"] }}'
      unit_of_measurement: 'FPS'
    frigate_coral_inference:
      value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["inference_speed"] }}' 
      unit_of_measurement: 'ms'