- platform: rest
  name: Frigate Debug
  resource: !secret frigate_debug_states_url
  scan_interval: 5
  json_attributes:
    - living_room
    - storage_room
    - front_door
    - garage_small_bay
    - coral
  value_template: 'OK'

- platform: template
  sensors:
    living_room_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["living_room"]["camera_fps"] }}'
      unit_of_measurement: 'FPS'
    living_room_skipped_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["living_room"]["skipped_fps"] }}'
      unit_of_measurement: 'FPS'
    living_room_detection_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["living_room"]["detection_fps"] }}'
      unit_of_measurement: 'FPS'
    storage_room_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["storage_room"]["camera_fps"] }}'
      unit_of_measurement: 'FPS'
    storage_room_skipped_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["storage_room"]["skipped_fps"] }}'
      unit_of_measurement: 'FPS'
    storage_room_detection_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["storage_room"]["detection_fps"] }}'
      unit_of_measurement: 'FPS'
    front_door_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["front_door"]["camera_fps"] }}'
      unit_of_measurement: 'FPS'
    front_door_skipped_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["front_door"]["skipped_fps"] }}'
      unit_of_measurement: 'FPS'
    front_door_detection_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["front_door"]["detection_fps"] }}'
      unit_of_measurement: 'FPS'
    garage_small_bay_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["garage_small_bay"]["camera_fps"] }}'
      unit_of_measurement: 'FPS'
    garage_small_bay_skipped_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["garage_small_bay"]["skipped_fps"] }}'
      unit_of_measurement: 'FPS'
    garage_small_bay_detection_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["garage_small_bay"]["detection_fps"] }}'
      unit_of_measurement: 'FPS'