- platform: template
  sensors:
    master_bedroom_shade_battery_level:
      friendly_name: 'Master Bedroom Shade Battery Level'
      value_template: '{{state_attr("cover.master_bedroom_shade", "battery_level")}}'
      unit_of_measurement: "%"
      device_class: battery