- platform: template
  sensors:
    ender_3_pro_time_elapsed_friendly:
      friendly_name: "Time Elapsed"
      entity_id: sensor.ender_3_pro_time_elapsed
      value_template: "{{ states('sensor.ender_3_pro_time_elapsed') | int | timestamp_custom('%H:%M:%S', 0) }}"

    ender_3_pro_time_remaining_friendly:
      friendly_name: "Time Remaining"
      entity_id: sensor.ender_3_pro_time_remaining
      value_template: "{{ states('sensor.ender_3_pro_time_remaining') | int | timestamp_custom('%H:%M:%S', 0) }}"