
- platform: template
  sensors:
    guest_count:
      friendly_name: Guest Count
      value_template: >-
        {{ states.device_tracker | selectattr('attributes.is_guest', 'eq', true) | selectattr('state', 'ne', 'not_home') | list | count }}
    
    guest_names:
      friendly_name: Guest Names
      value_template: >-
        {{ states.device_tracker | selectattr('attributes.is_guest', 'eq', true) | selectattr('state', 'ne', 'not_home') | map(attribute='name') | list }}