- host: !secret camera_amcrest_ip
  name: !secret camera_amcrest_name
  username: !secret camera_username
  password: !secret camera_password
  resolution: high
  stream_source: rtsp
  control_light: false
  binary_sensors:
    - motion_detected
    - online
  sensors:
    - sdcard
    - ptz_preset