- platform: template
  sensors:
    august_smart_lock_gen3_front_door_battery_level:
      device_class: battery
      entity_id: zwave.august_smart_lock_gen3_front_door
      friendly_name: 'Front Door Lock Battery Level'
      value_template: >
        {% if states.zwave.august_smart_lock_gen3_front_door.attributes.battery_level is defined %}
          {{ states.zwave.august_smart_lock_gen3_front_door.attributes.battery_level|float <= 15 }}
        {% else %}
          false
        {% endif %}

    august_smart_lock_gen3_front_door_locked:
      device_class: lock
      entity_id: lock.august_smart_lock_gen3_front_door_locked
      friendly_name: 'Front Door Locked'
      value_template: "{{ is_state('lock.august_smart_lock_gen3_front_door_locked', 'unlocked') }}"

#    house_front_door:
#      device_class: door
#      entity_id: sensor.august_smart_lock_gen3_front_door_access_control
#      friendly_name: 'Front Door Lock Battery Level'
#      value_template: "{{ is_state('sensor.august_smart_lock_gen3_front_door_access_control', '2') }}"

- platform: template
  sensors:
    back_hallway_motion_switch_motion:
      device_class: motion
      entity_id: sensor.back_hallway_motion_switch_burglar
      friendly_name: 'Back Hallway Motion'
      value_template: "{{ is_state('sensor.back_hallway_motion_switch_burglar', '8') }}"

    back_hallway_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.back_hallway_motion_switch_burglar
      friendly_name: 'Back Hallway Occupancy'
      value_template: "{{ is_state('sensor.back_hallway_motion_switch_burglar', '8') }}"

    front_door_can_motion_switch_motion:
      device_class: motion
      entity_id: sensor.front_door_can_motion_switch_burglar
      friendly_name: 'Front Door Can Motion'
      value_template: "{{ is_state('sensor.front_door_can_motion_switch_burglar', '8') }}"

    front_door_can_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.front_door_can_motion_switch_burglar
      friendly_name: 'Front Door Can Occupancy'
      value_template: "{{ is_state('sensor.front_door_can_motion_switch_burglar', '8') }}"

    front_foyer_motion_switch_motion:
      device_class: motion
      entity_id: sensor.front_foyer_motion_switch_burglar
      friendly_name: 'Front Foyer Motion'
      value_template: "{{ is_state('sensor.front_foyer_motion_switch_burglar', '8') }}"

    front_foyer_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.front_foyer_motion_switch_burglar
      friendly_name: 'Front Foyer Occupancy'
      value_template: "{{ is_state('sensor.front_foyer_motion_switch_burglar', '8') }}"

    front_foyer_right_closet_motion_switch_motion:
      device_class: motion
      entity_id: sensor.front_foyer_right_closet_motion_switch_burglar
      friendly_name: 'Front Foyer Right Closet Motion'
      value_template: "{{ is_state('sensor.front_foyer_right_closet_motion_switch_burglar', '8') }}"

    front_foyer_right_closet_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.front_foyer_right_closet_motion_switch_burglar
      friendly_name: 'Front Foyer Right Closet Occupancy'
      value_template: "{{ is_state('sensor.front_foyer_right_closet_motion_switch_burglar', '8') }}"

    kitchen_main_lights_motion_switch_motion:
      device_class: motion
      entity_id: sensor.kitchen_main_lights_motion_switch_burglar
      friendly_name: 'Kitchen Main Lights Motion'
      value_template: "{{ is_state('sensor.kitchen_main_lights_motion_switch_burglar', '8') }}"

    kitchen_main_lights_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.kitchen_main_lights_motion_switch_burglar
      friendly_name: 'Kitchen Main Lights Occupancy'
      value_template: "{{ is_state('sensor.kitchen_main_lights_motion_switch_burglar', '8') }}"

    kitchen_sink_lights_motion_switch_motion:
      device_class: motion
      entity_id: sensor.kitchen_sink_lights_motion_dimmer_burglar
      friendly_name: 'Kitchen Sink Lights Motion'
      value_template: "{{ is_state('sensor.kitchen_sink_lights_motion_dimmer_burglar', '8') }}"

    kitchen_sink_lights_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.kitchen_sink_lights_motion_dimmer_burglar
      friendly_name: 'Kitchen Sink Lights Occupancy'
      value_template: "{{ is_state('sensor.kitchen_sink_lights_motion_dimmer_burglar', '8') }}"

    master_bedroom_closet_motion_switch_motion:
      device_class: motion
      entity_id: sensor.master_bedroom_closet_motion_switch_burglar
      friendly_name: 'Master Bedroom Closet Motion'
      value_template: "{{ is_state('sensor.master_bedroom_closet_motion_switch_burglar', '8') }}"

    master_bedroom_closet_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.master_bedroom_closet_motion_switch_burglar
      friendly_name: 'Master Bedroom Closet Occupancy'
      value_template: "{{ is_state('sensor.master_bedroom_closet_motion_switch_burglar', '8') }}"

    upstairs_hallway_motion_switch_motion:
      device_class: motion
      entity_id: sensor.upstairs_hallway_motion_switch_burglar
      friendly_name: 'Upstairs Hallway Motion'
      value_template: "{{ is_state('sensor.upstairs_hallway_motion_switch_burglar', '8') }}"

    upstairs_hallway_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.upstairs_hallway_motion_switch_burglar
      friendly_name: 'Upstairs Hallway Occupancy'
      value_template: "{{ is_state('sensor.upstairs_hallway_motion_switch_burglar', '8') }}"