- platform: template
  sensors:
    front_door_locked_battery_level:
      device_class: battery
      entity_id: zwave.front_door_lock
      friendly_name: 'Front Door Lock Battery Level'
      value_template: >
        {% if states.zwave.front_door_lock.attributes.battery_level is defined %}
          {{ states.zwave.front_door_lock.attributes.battery_level|float <= 15 }}
        {% else %}
          false
        {% endif %}

    front_door_locked:
      device_class: lock
      entity_id: lock.front_door_locked
      friendly_name: 'Front Door Locked'
      value_template: "{{ is_state('lock.front_door_locked', 'unlocked') }}"

#    house_front_door:
#      device_class: door
#      entity_id: sensor.front_door_lock_access_control
#      friendly_name: 'Front Door Lock Battery Level'
#      value_template: "{{ is_state('sensor.front_door_lock_access_control', '2') }}"

    back_foyer_door_locked_battery_level:
      device_class: battery
      entity_id: zwave.back_foyer_door_lock
      friendly_name: 'Back Foyer Door Lock Battery Level'
      value_template: >
        {% if states.zwave.back_foyer_door_lock.attributes.battery_level is defined %}
          {{ states.zwave.back_foyer_door_lock.attributes.battery_level|float <= 15 }}
        {% else %}
          false
        {% endif %}

    back_foyer_door_locked:
      device_class: lock
      entity_id: lock.back_foyer_door_locked
      friendly_name: 'Back Foyer Door Locked'
      value_template: "{{ is_state('lock.back_foyer_door_locked', 'unlocked') }}"

    exercise_room_door_locked_battery_level:
      device_class: battery
      entity_id: zwave.exercise_room_door_lock
      friendly_name: 'Exercise Room Door Lock Battery Level'
      value_template: >
        {% if states.zwave.exercise_room_door_lock.attributes.battery_level is defined %}
          {{ states.zwave.exercise_room_door_lock.attributes.battery_level|float <= 15 }}
        {% else %}
          false
        {% endif %}

    exercise_room_door_locked:
      device_class: lock
      entity_id: lock.exersize_room_door_locked
      friendly_name: 'Exercise Room Door Locked'
      value_template: "{{ is_state('lock.exersize_room_door_locked', 'unlocked') }}"

- platform: template
  sensors:
    family_room_motion_switch_motion:
      device_class: motion
      entity_id: sensor.family_room_motion_switch_burglar
      friendly_name: 'Family Room Motion'
      value_template: "{{ is_state('sensor.family_room_motion_switch_burglar', '8') }}"

    family_room_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.family_room_motion_switch_burglar
      friendly_name: 'Family Room Occupancy'
      value_template: "{{ is_state('sensor.family_room_motion_switch_burglar', '8') }}"

    storage_room_motion_switch_motion:
      device_class: motion
      entity_id: sensor.storage_room_motion_switch_burglar
      friendly_name: 'Storage Room Motion'
      value_template: "{{ is_state('sensor.storage_room_motion_switch_burglar', '8') }}"

    storage_room_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.storage_room_motion_switch_burglar
      friendly_name: 'Storage Room Occupancy'
      value_template: "{{ is_state('sensor.storage_room_motion_switch_burglar', '8') }}"

    back_hallway_motion_switch_motion:
      device_class: motion
      entity_id: sensor.back_hallway_motion_switch_burglar
      friendly_name: 'Back Hallway Motion'
      value_template: "{{ is_state('sensor.back_hallway_motion_switch_burglar', '8') }}"

    back_hallway_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.back_hallway_motion_switch_burglar
      friendly_name: 'Back Hallway Occupancy'
      value_template: "{{ is_state('sensor.back_hallway_motion_switch_burglar', '8') }}"

    front_door_can_motion_switch_motion:
      device_class: motion
      entity_id: sensor.front_door_can_motion_switch_burglar
      friendly_name: 'Front Door Can Motion'
      value_template: "{{ is_state('sensor.front_door_can_motion_switch_burglar', '8') }}"

    front_door_can_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.front_door_can_motion_switch_burglar
      friendly_name: 'Front Door Can Occupancy'
      value_template: "{{ is_state('sensor.front_door_can_motion_switch_burglar', '8') }}"

    front_foyer_motion_switch_motion:
      device_class: motion
      entity_id: sensor.front_foyer_motion_switch_burglar
      friendly_name: 'Front Foyer Motion'
      value_template: "{{ is_state('sensor.front_foyer_motion_switch_burglar', '8') }}"

    front_foyer_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.front_foyer_motion_switch_burglar
      friendly_name: 'Front Foyer Occupancy'
      value_template: "{{ is_state('sensor.front_foyer_motion_switch_burglar', '8') }}"

    front_foyer_right_closet_motion_switch_motion:
      device_class: motion
      entity_id: sensor.front_foyer_right_closet_motion_switch_burglar
      friendly_name: 'Front Foyer Right Closet Motion'
      value_template: "{{ is_state('sensor.front_foyer_right_closet_motion_switch_burglar', '8') }}"

    front_foyer_right_closet_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.front_foyer_right_closet_motion_switch_burglar
      friendly_name: 'Front Foyer Right Closet Occupancy'
      value_template: "{{ is_state('sensor.front_foyer_right_closet_motion_switch_burglar', '8') }}"

    kitchen_main_lights_motion_switch_motion:
      device_class: motion
      entity_id: sensor.kitchen_main_lights_motion_switch_burglar
      friendly_name: 'Kitchen Main Lights Motion'
      value_template: "{{ is_state('sensor.kitchen_main_lights_motion_switch_burglar', '8') }}"

    kitchen_main_lights_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.kitchen_main_lights_motion_switch_burglar
      friendly_name: 'Kitchen Main Lights Occupancy'
      value_template: "{{ is_state('sensor.kitchen_main_lights_motion_switch_burglar', '8') }}"

    kitchen_sink_lights_motion_switch_motion:
      device_class: motion
      entity_id: sensor.kitchen_sink_lights_motion_dimmer_burglar
      friendly_name: 'Kitchen Sink Lights Motion'
      value_template: "{{ is_state('sensor.kitchen_sink_lights_motion_dimmer_burglar', '8') }}"

    kitchen_sink_lights_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.kitchen_sink_lights_motion_dimmer_burglar
      friendly_name: 'Kitchen Sink Lights Occupancy'
      value_template: "{{ is_state('sensor.kitchen_sink_lights_motion_dimmer_burglar', '8') }}"

    master_bedroom_closet_motion_switch_motion:
      device_class: motion
      entity_id: sensor.master_bedroom_closet_motion_dimmer_burglar
      friendly_name: 'Master Bedroom Closet Motion'
      value_template: "{{ is_state('sensor.master_bedroom_closet_motion_dimmer_burglar', '8') }}"

    master_bedroom_closet_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.master_bedroom_closet_motion_dimmer_burglar
      friendly_name: 'Master Bedroom Closet Occupancy'
      value_template: "{{ is_state('sensor.master_bedroom_closet_motion_dimmer_burglar', '8') }}"

    upstairs_hallway_motion_switch_motion:
      device_class: motion
      entity_id: sensor.upstairs_hallway_motion_switch_burglar
      friendly_name: 'Upstairs Hallway Motion'
      value_template: "{{ is_state('sensor.upstairs_hallway_motion_switch_burglar', '8') }}"

    upstairs_hallway_motion_switch_occupancy:
      device_class: occupancy
      entity_id: sensor.upstairs_hallway_motion_switch_burglar
      friendly_name: 'Upstairs Hallway Occupancy'
      value_template: "{{ is_state('sensor.upstairs_hallway_motion_switch_burglar', '8') }}"

- platform: template
  sensors:
    basement_utility_room_nest_protect_battery_health:
      device_class: battery
      entity_id: sensor.basement_utility_room_nest_protect_battery_health
      friendly_name: 'Utility Room Nest Battery'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_battery_health', 'Ok') }}"

    basement_utility_room_nest_protect_smoke_status:
      device_class: smoke
      entity_id: sensor.basement_utility_room_nest_protect_smoke_status
      friendly_name: 'Utility Room Nest Smoke Status'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_smoke_status', 'Ok') }}"

    basement_utility_room_nest_protect_co_status:
      device_class: gas
      entity_id: sensor.basement_utility_room_nest_protect_co_status
      friendly_name: 'Utility Room Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_co_status', 'Ok') }}"

    basement_utility_room_nest_protect_status:
      device_class: problem
      entity_id: sensor.basement_utility_room_nest_protect_color_status
      friendly_name: 'Utility Room Nest Status'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_color_status', 'green') }}"

    hallway_nest_protect_battery_health:
      device_class: battery
      entity_id: sensor.hallway_nest_protect_battery_health
      friendly_name: 'Back Hallway Nest Battery'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_battery_health', 'Ok') }}"

    hallway_nest_protect_smoke_status:
      device_class: smoke
      entity_id: sensor.hallway_nest_protect_smoke_status
      friendly_name: 'Back Hallway Nest Smoke Status'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_smoke_status', 'Ok') }}"

    hallway_nest_protect_co_status:
      device_class: gas
      entity_id: sensor.hallway_nest_protect_co_status
      friendly_name: 'Back Hallway Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_co_status', 'Ok') }}"

    hallway_nest_protect_status:
      device_class: problem
      entity_id: sensor.hallway_nest_protect_color_status
      friendly_name: 'Office Nest Status'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_color_status', 'green') }}"

    office_nest_protect_battery_health:
      device_class: battery
      entity_id: sensor.office_nest_protect_battery_health
      friendly_name: 'Office Nest Battery'
      value_template: "{{ not is_state('sensor.office_nest_protect_battery_health', 'Ok') }}"

    office_nest_protect_smoke_status:
      device_class: smoke
      entity_id: sensor.office_nest_protect_smoke_status
      friendly_name: 'Office Nest Smoke Status'
      value_template: "{{ not is_state('sensor.office_nest_protect_smoke_status', 'Ok') }}"

    office_nest_protect_co_status:
      device_class: gas
      entity_id: sensor.office_nest_protect_co_status
      friendly_name: 'Office Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.office_nest_protect_co_status', 'Ok') }}"

    office_nest_protect_status:
      device_class: problem
      entity_id: sensor.office_nest_protect_color_status
      friendly_name: 'Office Nest Status'
      value_template: "{{ not is_state('sensor.office_nest_protect_color_status', 'green') }}"

    upstairs_nest_protect_battery_health:
      device_class: battery
      entity_id: sensor.upstairs_nest_protect_battery_health
      friendly_name: 'Upstairs Nest Battery'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_battery_health', 'Ok') }}"

    upstairs_nest_protect_smoke_status:
      device_class: smoke
      entity_id: sensor.upstairs_nest_protect_smoke_status
      friendly_name: 'Upstairs Nest Smoke Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_smoke_status', 'Ok') }}"

    upstairs_nest_protect_co_status:
      device_class: gas
      entity_id: sensor.upstairs_nest_protect_co_status
      friendly_name: 'Upstairs Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_co_status', 'Ok') }}"

    upstairs_nest_protect_status:
      device_class: problem
      entity_id: sensor.upstairs_nest_protect_color_status
      friendly_name: 'Upstairs Nest Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_color_status', 'green') }}"

    upstairs_nest_protect_battery_health_2:
      device_class: battery
      entity_id: sensor.upstairs_nest_protect_battery_health_2
      friendly_name: 'Upstairs Nest Battery'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_battery_health_2', 'Ok') }}"

    upstairs_nest_protect_smoke_status_2:
      device_class: smoke
      entity_id: sensor.upstairs_nest_protect_smoke_status_2
      friendly_name: 'Upstairs Nest Smoke Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_smoke_status_2', 'Ok') }}"

    upstairs_nest_protect_co_status_2:
      device_class: gas
      entity_id: sensor.upstairs_nest_protect_co_status_2
      friendly_name: 'Upstairs Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_co_status_2', 'Ok') }}"

    upstairs_nest_protect_status_2:
      device_class: problem
      entity_id: sensor.upstairs_nest_protect_color_status_2
      friendly_name: 'Upstairs Nest Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_color_status_2', 'green') }}"

    master_bedroom_nest_protect_battery_health:
      device_class: battery
      entity_id: sensor.master_bedroom_nest_protect_battery_health
      friendly_name: 'Master Bedroom Nest Battery'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_battery_health', 'Ok') }}"

    master_bedroom_nest_protect_smoke_status:
      device_class: smoke
      entity_id: sensor.master_bedroom_nest_protect_smoke_status
      friendly_name: 'Master Bedroom Nest Smoke Status'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_smoke_status', 'Ok') }}"

    master_bedroom_nest_protect_co_status:
      device_class: gas
      entity_id: sensor.master_bedroom_nest_protect_co_status
      friendly_name: 'Master Bedroom Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_co_status', 'Ok') }}"

    master_bedroom_nest_protect_status:
      device_class: problem
      entity_id: sensor.master_bedroom_nest_protect_color_status
      friendly_name: 'Master Bedroom Nest Status'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_color_status', 'green') }}"

    kids_bedroom_one_nest_protect_battery_health:
      device_class: battery
      entity_id: sensor.kids_bedroom_one_nest_protect_battery_health
      friendly_name: 'Kid 1 Bedroom Nest Battery'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_battery_health', 'Ok') }}"

    kids_bedroom_one_nest_protect_smoke_status:
      device_class: smoke
      entity_id: sensor.kids_bedroom_one_nest_protect_smoke_status
      friendly_name: 'Kid 1 Bedroom Nest Smoke Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_smoke_status', 'Ok') }}"

    kids_bedroom_one_nest_protect_co_status:
      device_class: gas
      entity_id: sensor.kids_bedroom_one_nest_protect_co_status
      friendly_name: 'Kid 1 Bedroom Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_co_status', 'Ok') }}"

    kids_bedroom_one_nest_protect_status:
      device_class: problem
      entity_id: sensor.kids_bedroom_one_nest_protect_color_status
      friendly_name: 'Kid 1 Bedroom Nest Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_color_status', 'green') }}"

    kids_bedroom_two_nest_protect_battery_health:
      device_class: battery
      entity_id: sensor.kids_bedroom_two_nest_protect_battery_health
      friendly_name: 'Kid 2 Bedroom Nest Battery'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_battery_health', 'Ok') }}"

    kids_bedroom_two_nest_protect_smoke_status:
      device_class: smoke
      entity_id: sensor.kids_bedroom_two_nest_protect_smoke_status
      friendly_name: 'Kid 2 Bedroom Nest Smoke Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_smoke_status', 'Ok') }}"

    kids_bedroom_two_nest_protect_co_status:
      device_class: gas
      entity_id: sensor.kids_bedroom_two_nest_protect_co_status
      friendly_name: 'Kid 2 Bedroom Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_co_status', 'Ok') }}"

    kids_bedroom_two_nest_protect_status:
      device_class: problem
      entity_id: sensor.kids_bedroom_two_nest_protect_color_status
      friendly_name: 'Kid 2 Bedroom Nest Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_color_status', 'green') }}"

- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error