  - platform: unifi
    host: !secret unifi_host
    port: !secret unifi_port
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    track_new_devices: true
    ssid_filter:
      - !secret unifii_ssid_filter