#---------
# Seasonal
#---------
christmas_lights:
  name: Christmas Lights
  icon: mdi:pine-tree
  entities:
    - switch.front_door_north_outside_receptacle
    - switch.living_room_west_receptacle
    - switch.living_room_top_mantle_receptacle
#    - switch.entertainment_room_receptacle
#    - switch.living_room_wemo
#    - switch.outside_receptacle

#---------
# Other
#---------
packages:
  name: Packages Arriving
  icon: mdi:package
  entities:
    - sensor.packages_in_transit
    - sensor.deliveries_today
#    - sensor.fedex

printer:
  name: 3D Printer
  icon: mdi:printer-3d

#---------
# Garage
#---------
garage:
  name: Garage
  icon: mdi:gamepad
  entities:
    - group.gameroom
    - cover.left_garage_door

game_room:
  name: Game Room
  icon: mdi:garage
  entities:
    - light.game_room_thermostat

#---------
# Outside
#---------
outside:
  name: Outside
  icon: mdi:tree
  entities:
    - group.outside_lights
    - switch.outside_receptacle

outside_lights:
  name: Outside Lights
  icon: mdi:tree
  entities:
    - group.front_outside_lights
    - group.back_outside_lights

front_outside_lights:
  name: Front Outside Lights
  icon: mdi:tree
  entities:
    - switch.front_door_north_outside_receptacle
    - switch.front_door_can_motion_light
    - switch.front_foyer_wall_lights
    - switch.garage_front_outside_wall_light

front_outside_wall_lights:
  name: Front Outside Wall Lights
  icon: mdi:tree
  entities:
    - switch.front_foyer_wall_lights
    - switch.garage_front_outside_wall_light

back_outside_lights:
  name: Back Outside Lights
  icon: mdi:tree
  entities:
    - light.living_room_spot_lights
    - switch.living_room_wall_lights
    - switch.garage_small_bay_back_outside_light
    - switch.garage_big_bay_back_outside_light

#---------
# Basement
#---------
basement:
  name: Basement
  icon: mdi:floor-plan
  entities:
    - group.guest_bathroom
    - group.guest_bedroom
    - group.utility_room
    - group.exercise_room
    - group.family_room
    - group.storage_room

guest_bathroom:
  name: Guest Bathroom
  icon: mdi:toilet
  entities:
    - switch.guest_bathroom

guest_bedroom:
  name: Guest Bedroom
  icon: mdi:hotel
  entities:
    - switch.basement_bedroom
    - switch.basement_bedroom_closet_light

utility_room:
  name: Utility Room
  icon: mdi:wrench
  entities:
#    - camera.utility_room

exercise_room:
  name: Exercise Room
  icon: mdi:dumbbell
  entities:
    - switch.exercise_room_motion_light

family_room:
  name: Family Room
  icon: mdi:television
  entities:
    - light.family_room_lamp
    - switch.family_room_motion_light

storage_room:
  name: Stroage room
  icon: mdi:wrench
  entities:
    - switch.storage_room_motion_light

#---------
# First floor
#---------
firstfloor:
  name: First Floor
  icon: mdi:floor-plan
  entities:
    - group.front_foyer
    - group.living_room
    - group.entertainment_room
    - group.kitchen
    - group.wet_bar
    - group.laundry_room
    - group.office
    - group.bathroom
    - group.back_hallway
    - group.back_foyer

front_foyer:
  name: Foyer
  icon: mdi:sofa
  entities:
    - switch.front_foyer_motion_light
    - switch.front_foyer_right_closet_motion_light

living_room:
  name: Living Room
  icon: mdi:walk
  entities:
    - light.living_room_main_lights_inner
    - light.living_room_main_lights_outter
    - light.living_room_table
#    - switch.living_room_top_mantle_receptacle
#    - switch.living_room_bottom_mantle_receptacle
    - switch.living_room_west_receptacle
#    - switch.front_door_north_outside_receptacle

wet_bar:
  name: Wet Bar
  icon: mdi:beer-outline
  entities:
    - switch.living_room_top_wet_bar_light
    - switch.living_room_bottom_wet_bar_light

entertainment_room:
  name: Entertainment Room
  icon: mdi:television
  entities:
    - switch.entertainment_room
#    - switch.entertainment_room_receptacle

kitchen:
  name: Kitchen
  icon: mdi:fridge-outline
  entities:
    - switch.kitchen_bar_light
    - switch.kitchen_east_outside_receptacle
    - switch.kitchen_main_motion_light
    - light.kitchen_sink_motion_light

back_foyer:
  name: Back Foyer
  icon: mdi:walk
  entities:
    - switch.back_foyer

bathroom:
  name: Bathroom
  icon: mdi:toilet
  entities:
    - switch.first_floor_bathroom

back_hallway:
  name: Back Hallway
  icon: mdi:walk
  entities:
    - switch.back_hallway_closet_light
    - switch.back_hallway_picture_light
    - switch.back_hallway_motion_light

laundry_room:
  name: Laundry room
  icon: mdi:washing-machine
  entities:
    - switch.laundry_room

office:
  name: Office
  icon: mdi:desk-lamp
  entities:
    - light.office_lightstrip
    - switch.office_closet_main_lights
    - switch.office_switch
    - switch.office_wemo

#---------
# Second floor
#---------
second_floor:
  name: Second Floor
  icon: mdi:floor-plan
  entities:
    - group.upstairs_hallway
    - group.master_bedroom
    - group.master_bathroom
    - group.master_water_closet
    - group.kid_one_bedroom
    - group.kid_two_bedroom
    - group.kids_bathroom

upstairs_hallway:
  name: Upstairs Hallway
  icon: mdi:walk
  entities:
    - switch.upstairs_hallway_motion_light

master_bedroom:
  name: Master Bedroom
  icon: mdi:hotel
  entities:
    - light.master_bedroom_main_lights
    - light.master_bedroom_left_lamp
    - light.master_bedroom_right_lamp
    - light.master_bedroom_closet

master_bathroom:
  name: Master Bathroom
  icon: mdi:shower
  entities:
    - switch.master_bathroom
    - light.master_bathroom_shower_lights
    - light.master_bathroom_tub_lights

master_water_closet:
  name: Master Water Closet
  icon: mdi:toilet
  entities:
    - switch.master_water_closet

kid_one_bedroom:
  name: Kid 1 Bedroom
  icon: mdi:desk-lamp
  entities:
    - switch.kids_room_one
    - switch.kids_room_one_closet_main_lights

kid_two_bedroom:
  name: Kid 2 Bedroom
  icon: mdi:desk-lamp
  entities:
    - switch.kids_room_two
    - switch.kids_room_two_closet_main_lights
    - light.left_hue_white_lamp
    - light.right_hue_white_lamp

kids_bathroom:
  name: Kids Bathroom
  icon: mdi:toilet
  entities:
    - switch.kids_bathroom
    - light.kids_bathroom_tub_lights