- platform: group
  name: home
  services:
    - service: !secret notify_person_1
    - service: !secret notify_person_2

- platform: group
  name: audit
  services:
    - service: !secret notify_person_1