  - name: home
    platform: group
    services:
      - service: html5
  - name: garbage
    platform: group
    services:
      - service: html5
  - name: ecobee
    platform: ecobee
  - platform: alexa_media
    name: alexa_media