#- platform: glances
#  host: !secret glances_host
#  username: !secret glances_username
#  password: !secret glances_password
#  version: 3
#  resources:
#    - 'disk_use_percent'
#    - 'memory_use_percent'
#    - 'processor_load'

- platform: opensky
  radius: 5

#- platform: co2signal
#  token: !secret co2signal_token

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
    - type: last_boot

- platform: template
  sensors:
    last_alexa:
      value_template: >
        {%- for entity in states.media_player -%}
          {%- if state_attr(entity.entity_id, 'last_called') == True -%}
            {{ entity.entity_id }}
          {%- endif -%}
        {%- endfor -%}

- platform: template
  sensors:
    packages_in_transit:
      friendly_name: "Packages in Transit"
      value_template: >
        {% macro in_transit(sensor) %}
          {{sensor.state|int - delivered(sensor)|int}}
        {% endmacro %}
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
              0
          {% endif %}
        {% endmacro %}
        {{in_transit(states.sensor.ups)|int}}

    deliveries_today:
      friendly_name: "Today's Deliveries"
      value_template: >
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
              0
          {% endif %}
        {% endmacro %}
        {{delivered(states.sensor.ups)|int}}

- platform: template
  sensors:
    ender_3_pro_time_elapsed_friendly:
      friendly_name: "Time Elapsed"
      entity_id: sensor.ender_3_pro_time_elapsed
      value_template: "{{ states('sensor.ender_3_pro_time_elapsed') | int | timestamp_custom('%H:%M:%S', 0) }}"

    ender_3_pro_time_remaining_friendly:
      friendly_name: "Time Remaining"
      entity_id: sensor.ender_3_pro_time_remaining
      value_template: "{{ states('sensor.ender_3_pro_time_remaining') | int | timestamp_custom('%H:%M:%S', 0) }}"