- platform: glances
  version: 3
  resources:
    - 'disk_use_percent'
    - 'memory_use_percent'
    - 'processor_load'

- platform: template
  sensors:
    last_alexa:
      value_template: >
        {%- for entity in states.media_player -%}
          {%- if state_attr(entity.entity_id, 'last_called') == True -%}
            {{ entity.entity_id }}
          {%- endif -%}
        {%- endfor -%}

- platform: template
  sensors:
    packages_in_transit:
      friendly_name: "Packages in Transit"
      value_template: >
        {% macro in_transit(sensor) %}
          {{sensor.state|int - delivered(sensor)|int}}
        {% endmacro %}
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
              0
          {% endif %}
        {% endmacro %}
        {{in_transit(states.sensor.ups)|int}}

    deliveries_today:
      friendly_name: "Today's Deliveries"
      value_template: >
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
              0
          {% endif %}
        {% endmacro %}
        {{delivered(states.sensor.ups)|int}}