- name: !secret zone_1_name
  radius: !secret zone_1_radius
  latitude: !secret zone_1_latitude
  longitude: !secret zone_1_longitude
  icon: mdi:desktop-classic

- name: !secret zone_2_name
  radius: !secret zone_2_radius
  latitude: !secret zone_2_latitude
  longitude: !secret zone_2_longitude
  icon: mdi:bank