
- platform: template
  sensors:
    front_door_locked:
      device_class: lock
      entity_id: lock.front_door
      friendly_name: 'Front Door Locked'
      value_template: "{{ is_state('lock.front_door', 'unlocked') }}"

    back_foyer_door_locked:
      device_class: lock
      entity_id: lock.back_foyer_door
      friendly_name: 'Back Foyer Door Locked'
      value_template: "{{ is_state('lock.back_foyer_door', 'unlocked') }}"

    exercise_room_door_locked:
      device_class: lock
      entity_id: lock.exersize_room_door
      friendly_name: 'Exercise Room Door Locked'
      value_template: "{{ is_state('lock.exersize_room_door', 'unlocked') }}"