- platform: template
  sensors:
    climate_basement_fan:
      unique_id: climate_basement_fan
      friendly_name: Climate Basement Fan
      value_template: "{{ state_attr('climate.basement', 'fan') == 'on' }}"
      icon_template: >-
        {%- if state_attr('climate.basement', 'fan') == 'on' -%}
          mdi:fan
        {%- else -%}
          mdi:fan-off
        {%- endif -%}
    climate_main_floor_fan:
      unique_id: climate_main_floor_fan
      friendly_name: Climate Main Floor Fan
      value_template: "{{ state_attr('climate.main_floor', 'fan') == 'on' }}"
      icon_template: >-
        {%- if state_attr('climate.main_floor', 'fan') == 'on' -%}
          mdi:fan
        {%- else -%}
          mdi:fan-off
        {%- endif -%}
    climate_office_fan:
      unique_id: climate_office_fan
      friendly_name: Climate Office Fan
      value_template: "{{ state_attr('climate.office', 'fan') == 'on' }}"
      icon_template: >-
        {%- if state_attr('climate.office', 'fan') == 'on' -%}
          mdi:fan
        {%- else -%}
          mdi:fan-off
        {%- endif -%}
    climate_upstairs_fan:
      unique_id: climate_upstairs_fan
      friendly_name: Climate Upstairs Fan
      value_template: "{{ state_attr('climate.upstairs', 'fan') == 'on' }}"
      icon_template: >-
        {%- if state_attr('climate.upstairs', 'fan') == 'on' -%}
          mdi:fan
        {%- else -%}
          mdi:fan-off
        {%- endif -%}
    climate_house_fan:
      unique_id: climate_house_fan
      friendly_name: Climate House Fan
      value_template: >-
        {{ is_state('binary_sensor.climate_basement_fan', 'on')
            or is_state('binary_sensor.climate_main_floor_fan', 'on')
            or is_state('binary_sensor.climate_office_fan', 'on')
            or is_state('binary_sensor.climate_upstairs_fan', 'on') }}
      icon_template: >-
        {%- if is_state('binary_sensor.climate_basement_fan', 'on')
            or is_state('binary_sensor.climate_main_floor_fan', 'on')
            or is_state('binary_sensor.climate_office_fan', 'on')
            or is_state('binary_sensor.climate_upstairs_fan', 'on') -%}
          mdi:fan
        {%- else -%}
          mdi:fan-off
        {%- endif -%}
    climate_basement_heat:
      unique_id: climate_basement_heat
      device_class: heat
      friendly_name: Climate Basement Aux Heat
      value_template: "{{ state_attr('climate.basement', 'aux_heat') == 'on' }}"
    climate_main_floor_heat:
      unique_id: climate_main_floor_heat
      device_class: heat
      friendly_name: Climate Main Floor Aux Heat
      value_template: "{{ state_attr('climate.main_floor', 'aux_heat') == 'on' }}"
    climate_office_heat:
      unique_id: climate_office_heat
      device_class: heat
      friendly_name: Climate Office Aux Heat
      value_template: "{{ state_attr('climate.office', 'aux_heat') == 'on' }}"
    climate_upstairs_heat:
      unique_id: climate_upstairs_heat
      device_class: heat
      friendly_name: Climate Upstairs Aux Heat
      value_template: "{{ state_attr('climate.upstairs', 'aux_heat') == 'on' }}"
    climate_house_heat:
      unique_id: climate_house_heat
      device_class: heat
      friendly_name: Climate House Aux Heat
      value_template: >-
        {{ is_state('binary_sensor.climate_basement_heat', 'on')
            or is_state('binary_sensor.climate_main_floor_heat', 'on')
            or is_state('binary_sensor.climate_office_heat', 'on')
            or is_state('binary_sensor.climate_upstairs_heat', 'on') }}