- platform: mqtt
  name: Living Room Cat Motion
  device_class: motion
  state_topic: "frigate/living_room/cat"
  availability_topic: "frigate/available"
- platform: mqtt
  name: Living Room Person Motion
  device_class: motion
  state_topic: "frigate/living_room/person"
  availability_topic: "frigate/available"

- platform: mqtt
  name: Storage Room Cat Motion
  device_class: motion
  state_topic: "frigate/storage_room/cat"
  availability_topic: "frigate/available"
- platform: mqtt
  name: Storage Room Mouse Motion
  device_class: motion
  state_topic: "frigate/storage_room/mouse"
  availability_topic: "frigate/available"
- platform: mqtt
  name: Storage Room Person Motion
  device_class: motion
  state_topic: "frigate/storage_room/person"
  availability_topic: "frigate/available"

#- platform: mqtt
#  name: Front Door Cat Motion
#  device_class: motion
#  state_topic: "frigate/front_door/cat"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Mouse Motion
#  device_class: motion
#  state_topic: "frigate/front_door/mouse"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Person Motion
#  device_class: motion
#  state_topic: "frigate/front_door/person"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Bicycle Motion
#  device_class: motion
#  state_topic: "frigate/front_door/bicycle"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Motorcycle Motion
#  device_class: motion
#  state_topic: "frigate/front_door/motorcycle"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Car Motion
#  device_class: motion
#  state_topic: "frigate/front_door/car"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Truck Motion
#  device_class: motion
#  state_topic: "frigate/front_door/truck"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Bus Motion
#  device_class: motion
#  state_topic: "frigate/front_door/bus"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Bird Motion
#  device_class: motion
#  state_topic: "frigate/front_door/bird"
#  availability_topic: "frigate/available"
#- platform: mqtt
#  name: Front Door Dog Motion
#  device_class: motion
#  state_topic: "frigate/front_door/dog"
#  availability_topic: "frigate/available"