- platform: template
  sensors:
    back_hallway_motion:
      device_class: motion
      entity_id: sensor.back_hallway_motion_light_alarm_home_security
      friendly_name: Back Hallway Motion
      value_template: "{{ states('sensor.back_hallway_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.back_hallway_motion_light_alarm_home_security', 'unavailable') else False }}"

    exercise_room_motion:
      device_class: motion
      entity_id: sensor.exercise_room_motion_light_alarm_home_security
      friendly_name: Exercise Room Motion
      value_template: "{{ states('sensor.exercise_room_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.exercise_room_motion_light_alarm_home_security', 'unavailable') else False }}"

    family_room_motion:
      device_class: motion
      entity_id: sensor.family_room_motion_light_alarm_home_security
      friendly_name: Family Room Motion
      value_template: "{{ states('sensor.family_room_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.family_room_motion_light_alarm_home_security', 'unavailable') else False }}"

    front_door_motion:
      device_class: motion
      entity_id: sensor.front_door_can_motion_light_alarm_home_security
      friendly_name: Front Door Can Motion
      value_template: "{{ states('sensor.front_door_can_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.front_door_can_motion_light_alarm_home_security', 'unavailable') else False }}"

    front_foyer_motion:
      device_class: motion
      entity_id: sensor.front_foyer_motion_light_alarm_home_security
      friendly_name: Front Foyer Motion
      value_template: "{{ states('sensor.front_foyer_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.front_foyer_motion_light_alarm_home_security', 'unavailable') else False }}"

    front_foyer_right_closet_motion:
      device_class: motion
      entity_id: sensor.front_foyer_right_closet_motion_light_alarm_home_security
      friendly_name: Front Foyer Right Closet Motion
      value_template: "{{ states('sensor.front_foyer_right_closet_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.front_foyer_right_closet_motion_light_alarm_home_security', 'unavailable') else False }}"

    game_room_accent_motion:
      device_class: motion
      entity_id: sensor.game_room_accent_motion_light_alarm_home_security
      friendly_name: Game Room Accent Motion
      value_template: "{{ states('sensor.game_room_accent_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.game_room_accent_motion_light_alarm_home_security', 'unavailable') else False }}"

    game_room_poker_table_motion:
      device_class: motion
      entity_id: sensor.game_room_poker_table_motion_light_alarm_home_security
      friendly_name: Game Room Poker Table Motion
      value_template: "{{ states('sensor.game_room_poker_table_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.game_room_poker_table_motion_light_alarm_home_security', 'unavailable') else False }}"

    game_room_stairs_motion:
      device_class: motion
      entity_id: sensor.game_room_stairs_motion_light_alarm_home_security
      friendly_name: Game Room Stairs Motion
      value_template: "{{ states('sensor.game_room_stairs_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.game_room_stairs_motion_light_alarm_home_security', 'unavailable') else False }}"

    garage_foyer_motion:
      device_class: motion
      entity_id: sensor.garage_foyer_motion_light_alarm_home_security
      friendly_name: Garage Foyer Motion
      value_template: "{{ states('sensor.garage_foyer_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.garage_foyer_motion_light_alarm_home_security', 'unavailable') else False }}"

    garage_small_bay_bench_motion:
      device_class: motion
      entity_id: sensor.garage_small_bay_bench_motion_light_alarm_home_security
      friendly_name: Garage Small Bay Bench Motion
      value_template: "{{ states('sensor.garage_small_bay_bench_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.garage_small_bay_bench_motion_light_alarm_home_security', 'unavailable') else False }}"

    kitchen_main_motion:
      device_class: motion
      entity_id: sensor.kitchen_main_motion_light_alarm_home_security
      friendly_name: Kitchen Main Motion
      value_template: "{{ states('sensor.kitchen_main_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.kitchen_main_motion_light_alarm_home_security', 'unavailable') else False }}"

    kitchen_sink_motion:
      device_class: motion
      entity_id: sensor.kitchen_sink_motion_light_alarm_home_security
      friendly_name: Kitchen Sink Motion
      value_template: "{{ states('sensor.kitchen_sink_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.kitchen_sink_motion_light_alarm_home_security', 'unavailable') else False }}"

    master_bedroom_closet_motion:
      device_class: motion
      entity_id: sensor.master_bedroom_closet_motion_light_alarm_home_security
      friendly_name: Master Bedroom Closet Motion
      value_template: "{{ states('sensor.master_bedroom_closet_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.master_bedroom_closet_motion_light_alarm_home_security', 'unavailable') else False }}"

    storage_room_motion:
      device_class: motion
      entity_id: sensor.storage_room_motion_light_alarm_home_security
      friendly_name: Storage Room Motion
      value_template: "{{ states('sensor.storage_room_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.storage_room_motion_light_alarm_home_security', 'unavailable') else False }}"

    upstairs_hallway_motion:
      device_class: motion
      entity_id: sensor.upstairs_hallway_motion_light_alarm_home_security
      friendly_name: Upstairs Hallway Motion
      value_template: "{{ states('sensor.upstairs_hallway_motion_light_alarm_home_security').lower().startswith('motion detected') }}"
      availability_template: "{{ True if not is_state('sensor.upstairs_hallway_motion_light_alarm_home_security', 'unavailable') else False }}"