- platform: template
  sensors:
    basement_utility_room_nest_protect_battery_health:
      unique_id: basement_utility_room_nest_protect_battery_health
      device_class: battery
      friendly_name: 'Utility Room Nest Battery'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_battery_health', 'Ok') }}"

    basement_utility_room_nest_protect_smoke_status:
      unique_id: basement_utility_room_nest_protect_smoke_status
      device_class: smoke
      friendly_name: 'Utility Room Nest Smoke Status'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_smoke_status', 'Ok') }}"

    basement_utility_room_nest_protect_co_status:
      unique_id: basement_utility_room_nest_protect_co_status
      device_class: gas
      friendly_name: 'Utility Room Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_co_status', 'Ok') }}"

    basement_utility_room_nest_protect_status:
      unique_id: basement_utility_room_nest_protect_status
      device_class: problem
      friendly_name: 'Utility Room Nest Status'
      value_template: "{{ not is_state('sensor.basement_utility_room_nest_protect_color_status', 'green') }}"

    hallway_nest_protect_battery_health:
      unique_id: hallway_nest_protect_battery_health
      device_class: battery
      friendly_name: 'Back Hallway Nest Battery'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_battery_health', 'Ok') }}"

    hallway_nest_protect_smoke_status:
      unique_id: hallway_nest_protect_smoke_status
      device_class: smoke
      friendly_name: 'Back Hallway Nest Smoke Status'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_smoke_status', 'Ok') }}"

    hallway_nest_protect_co_status:
      unique_id: hallway_nest_protect_co_status
      device_class: gas
      friendly_name: 'Back Hallway Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_co_status', 'Ok') }}"

    hallway_nest_protect_status:
      unique_id: hallway_nest_protect_status
      device_class: problem
      friendly_name: 'Office Nest Status'
      value_template: "{{ not is_state('sensor.hallway_nest_protect_color_status', 'green') }}"

    office_nest_protect_battery_health:
      unique_id: office_nest_protect_battery_health
      device_class: battery
      friendly_name: 'Office Nest Battery'
      value_template: "{{ not is_state('sensor.office_nest_protect_battery_health', 'Ok') }}"

    office_nest_protect_smoke_status:
      unique_id: office_nest_protect_smoke_status
      device_class: smoke
      friendly_name: 'Office Nest Smoke Status'
      value_template: "{{ not is_state('sensor.office_nest_protect_smoke_status', 'Ok') }}"

    office_nest_protect_co_status:
      unique_id: office_nest_protect_co_status
      device_class: gas
      friendly_name: 'Office Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.office_nest_protect_co_status', 'Ok') }}"

    office_nest_protect_status:
      unique_id: office_nest_protect_status
      device_class: problem
      friendly_name: 'Office Nest Status'
      value_template: "{{ not is_state('sensor.office_nest_protect_color_status', 'green') }}"

    upstairs_nest_protect_battery_health:
      unique_id: upstairs_nest_protect_battery_health
      device_class: battery
      friendly_name: 'Upstairs Nest Battery'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_battery_health', 'Ok') }}"

    upstairs_nest_protect_smoke_status:
      unique_id: upstairs_nest_protect_smoke_status
      device_class: smoke
      friendly_name: 'Upstairs Nest Smoke Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_smoke_status', 'Ok') }}"

    upstairs_nest_protect_co_status:
      unique_id: upstairs_nest_protect_co_status
      device_class: gas
      friendly_name: 'Upstairs Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_co_status', 'Ok') }}"

    upstairs_nest_protect_status:
      unique_id: upstairs_nest_protect_status
      device_class: problem
      friendly_name: 'Upstairs Nest Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_color_status', 'green') }}"

    upstairs_nest_protect_battery_health_2:
      unique_id: upstairs_nest_protect_battery_health_2
      device_class: battery
      friendly_name: 'Upstairs Nest Battery'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_battery_health_2', 'Ok') }}"

    upstairs_nest_protect_smoke_status_2:
      unique_id: upstairs_nest_protect_smoke_status_2
      device_class: smoke
      friendly_name: 'Upstairs Nest Smoke Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_smoke_status_2', 'Ok') }}"

    upstairs_nest_protect_co_status_2:
      unique_id: upstairs_nest_protect_co_status_2
      device_class: gas
      friendly_name: 'Upstairs Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_co_status_2', 'Ok') }}"

    upstairs_nest_protect_status_2:
      unique_id: upstairs_nest_protect_status_2
      device_class: problem
      friendly_name: 'Upstairs Nest Status'
      value_template: "{{ not is_state('sensor.upstairs_nest_protect_color_status_2', 'green') }}"

    master_bedroom_nest_protect_battery_health:
      unique_id: master_bedroom_nest_protect_battery_health
      device_class: battery
      friendly_name: 'Master Bedroom Nest Battery'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_battery_health', 'Ok') }}"

    master_bedroom_nest_protect_smoke_status:
      unique_id: master_bedroom_nest_protect_smoke_status
      device_class: smoke
      friendly_name: 'Master Bedroom Nest Smoke Status'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_smoke_status', 'Ok') }}"

    master_bedroom_nest_protect_co_status:
      unique_id: master_bedroom_nest_protect_co_status
      device_class: gas
      friendly_name: 'Master Bedroom Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_co_status', 'Ok') }}"

    master_bedroom_nest_protect_status:
      unique_id: master_bedroom_nest_protect_status
      device_class: problem
      friendly_name: 'Master Bedroom Nest Status'
      value_template: "{{ not is_state('sensor.master_bedroom_nest_protect_color_status', 'green') }}"

    kids_bedroom_one_nest_protect_battery_health:
      unique_id: kids_bedroom_one_nest_protect_battery_health
      device_class: battery
      friendly_name: 'Kid 1 Bedroom Nest Battery'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_battery_health', 'Ok') }}"

    kids_bedroom_one_nest_protect_smoke_status:
      unique_id: kids_bedroom_one_nest_protect_smoke_status
      device_class: smoke
      friendly_name: 'Kid 1 Bedroom Nest Smoke Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_smoke_status', 'Ok') }}"

    kids_bedroom_one_nest_protect_co_status:
      unique_id: kids_bedroom_one_nest_protect_co_status
      device_class: gas
      friendly_name: 'Kid 1 Bedroom Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_co_status', 'Ok') }}"

    kids_bedroom_one_nest_protect_status:
      unique_id: kids_bedroom_one_nest_protect_status
      device_class: problem
      friendly_name: 'Kid 1 Bedroom Nest Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_one_nest_protect_color_status', 'green') }}"

    kids_bedroom_two_nest_protect_battery_health:
      unique_id: kids_bedroom_two_nest_protect_battery_health
      device_class: battery
      friendly_name: 'Kid 2 Bedroom Nest Battery'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_battery_health', 'Ok') }}"

    kids_bedroom_two_nest_protect_smoke_status:
      unique_id: kids_bedroom_two_nest_protect_smoke_status
      device_class: smoke
      friendly_name: 'Kid 2 Bedroom Nest Smoke Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_smoke_status', 'Ok') }}"

    kids_bedroom_two_nest_protect_co_status:
      unique_id: kids_bedroom_two_nest_protect_co_status
      device_class: gas
      friendly_name: 'Kid 2 Bedroom Nest Carbon Monoxide Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_co_status', 'Ok') }}"

    kids_bedroom_two_nest_protect_status:
      unique_id: kids_bedroom_two_nest_protect_status
      device_class: problem
      friendly_name: 'Kid 2 Bedroom Nest Status'
      value_template: "{{ not is_state('sensor.kids_bedroom_two_nest_protect_color_status', 'green') }}"